flags: {}
packages:
- '.'

- location:
    git: https://github.com/OlivierSohn/bindings-GLFW.git
    commit: f04f9cd23aab48ac4dcd456736d298ce863d905c
  extra-dep: true

extra-deps: []
resolver: lts-5.2
