flags: {}
packages:
- '.'

- location:
    git: https://github.com/OlivierSohn/bindings-GLFW.git
    commit: 02d8896984607e98de5a8b46872b8939863637af
  extra-dep: true

extra-deps: []
resolver: lts-10.2
